version: '3'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=my_database
    ports: 
      - "3308:3306"
    networks:
      - emp-network
    volumes:
      - "./database/sql-scripts:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql:rw"
      
  spring-boot-jpa-app:
    image: spring-boot-apis
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/my_database?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=test123
    ports:
      - 8080:8080
    networks:
      - emp-network
    volumes:
      - ./logs:/spring-boot-apis/logs
      
  angular-ui:
    image: victoryssmile/angular-app:monolithic
    ports:
      - "80:80"
    networks:
      - emp-network
    depends_on:
      - spring-boot-jpa-app
      
networks:
  emp-network:
    driver: bridge