version: '3'
services:
  angular-ui:
    image: victoryssmile/angular-app:monolithic-cloud
    ports: 
      - "80:80"
    networks:
      - emp-network
    depends_on:
      - spring-boot-jpa-app
      
  spring-boot-jpa-app:
    image: victoryssmile/spring-boot-apis:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://aws-mysql.c8ebmuzjtso3.ca-central-1.rds.amazonaws.com:3306/my_database?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root12345
    ports:
      - 8080:8080
    networks:
      - emp-network
      
networks:
  emp-network:
    driver: bridge 